// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WorkoutStep { set_point: number, target_power: [number, number], target_cadence: [number, number] | null, duration: number, }