// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkoutStep } from "./WorkoutStep";

export interface Workout { title: string, steps: Array<WorkoutStep>, }